<template>
  <div class="bg-gray-50 min-h-screen py-12">
    <div class="max-w-5xl mx-auto bg-white shadow-lg rounded-lg p-8 sm:p-12">
      <!-- Page Title -->
      <h1 class="text-4xl font-extrabold text-gray-800 text-center mb-4">
        Terms and Conditions
      </h1>
      <p class="text-sm text-gray-500 text-center mb-8">
        As updated on <span class="font-medium">14th December 2024</span>
      </p>

      <!-- Content -->
      <div class="space-y-12">
        <!-- Introduction -->
        <section>
          <h2
            class="text-2xl font-semibold text-gray-700 mb-4 border-b-2 border-blue-500 pb-2"
          >
            Introduction and Acknowledgment
          </h2>
          <p class="text-gray-600 leading-relaxed">
            These terms of use (“Terms”) mandate the terms on which the users
            (“You” or “Your” or “User”) access and register on the web-based
            platform www.upshotbrandmedia.com and mobile application ‘Upshot
            Brand Media’ (collectively, the “Platform”), operated and managed by
            Upshot Brand Media LLP, a company having its registered office at
            12/4, Film Colony, Film Colony Area, Indore, Madhya Pradesh, India -
            452001 and its subsidiaries under the registered trademark ‘Upshot
            Brand Media’.
          </p>
          <p class="text-gray-600 leading-relaxed mt-4">
            That the Company has granted a worldwide, non-exclusive,
            non-sublicensable, non-transferable and non-assignable license to
            the subsidiary to access, use, manage and operate the Platform and
            use the Company’s intellectual property in relation to its use on
            the Platform.
          </p>
          <p class="text-gray-600 leading-relaxed mt-4">
            This Terms is an electronic record in terms of the Information
            Technology Act, 2000 and rules made thereunder as applicable. The
            Terms is (i) published in accordance with the provisions of Rule
            3(1)(a) of the Information Technology (Intermediary Guidelines and
            Digital Media Ethics Code) Rules, 2021 and (ii) generated by a
            computer system and does not require any physical, electronic, or
            digital signatures by the Company.
          </p>
        </section>

        <!-- Definitions -->
        <section>
          <h2
            class="text-2xl font-semibold text-gray-700 mb-4 border-b-2 border-blue-500 pb-2"
          >
            Definitions and Interpretation
          </h2>
          <p class="text-gray-600 leading-relaxed">
            Unless the context otherwise requires, for these Terms, the
            following terms shall have the meaning ascribed to them hereunder:
          </p>
          <div class="mt-4 space-y-4">
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600"
                  >“Applicable Law”:</span
                >
                means all laws, ordinances, statutes, rules, orders, decrees,
                injunctions, licenses, permits, approvals, authorizations,
                consents, waivers, privileges, agreements, and regulations of
                any governmental authority/court of law having jurisdiction in
                India over the relevant matter including any interpretations
                thereof, in effect, including but not limited to, Information
                Technology Act, 2000 and the rules made thereunder, Digital
                Personal Data Protection Act, 2023.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600">“Content”:</span>
                shall mean any content, including but not limited to, pictures,
                messages, videos that may be shared, uploaded and posted on the
                Platform by the User.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600"
                  >“Eligibility Conditions”:</span
                >
                shall have the meaning as ascribed to under Clause 2.7.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600">“Company IP”:</span>
                shall have the meaning as ascribed to under Clause 7.1.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600"
                  >“Intellectual Property Rights”:</span
                >
                means all patents, designs and drawings, trademarks, service
                marks, logos, domain names, and utility models, copyrights,
                inventions, brand names, and business names, and any similar
                rights and the benefit (subject to the burden) of any of the
                foregoing (in each case whether registered or otherwise, and
                includes applications for the grant of any of the foregoing and
                the right to apply for any of the foregoing in any part of the
                world).
              </p>
            </div>

            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600">“Materials”:</span>
                includes (i) the text, software, scripts, graphics, photos,
                sounds, music, videos, audio-visual combinations, interactive
                features and other materials and (ii) comments and Content that
                You may contribute in any manner on a particular section of
                Platform via features or functionalities to the Platform.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600"
                  >“Privacy Policy”:</span
                >
                shall mean the Privacy Policy available on the Platform.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600"
                  >“Personal Data”:</span
                >
                shall have the meaning as ascribed to under Clause 2.3.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600">"Services":</span>
                shall have the meaning as ascribed under Clause 3.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600"
                  >“User / Users / You”:</span
                >
                shall mean and include any such User who visits the Platform or
                any user who wishes to avail Services through our Platform
                whether registered or not on the Platform and shall not include
                your permitted assigns, successors, heirs, and legal
                representatives, unless the context requires otherwise.
              </p>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-sm">
              <p class="text-gray-700">
                <span class="font-semibold text-blue-600">“User Account”:</span>
                means the personal online account created by the User to gain
                access and use the Platform.
              </p>
            </div>
          </div>
        </section>

         <section>
        <h2
        class="text-2xl font-semibold text-gray-700 mb-1 border-b-2 border-blue-500 pb-2">
        USER ACCOUNT AND USER OBLIGATIONS
      </h2>
        <p class="text-gray-600 leading-relaxed mb-1">
         
          <br />
          The User may view and/or access the Services or the Platform by simply visiting the Platform and clicking on relevant pages that include articles, newsletters. Furthermore, to access certain other Services, the User must first create a User Account with the Platform by providing details, including Personal Data as may be required by the Company and provided for in the Privacy Policy.
        </p>
        
        <p class="text-gray-600 leading-relaxed mb-4">
          <strong>Confidentiality Obligation:</strong> User shall be responsible for maintaining the confidentiality of the credentials of User Account, and furthermore, Company shall process and maintain the confidentiality of the Personal Data (defined) in accordance with the Applicable Law and is dealt in detail in the Privacy Policy of Company.
        </p>
  
        <p class="text-gray-600 leading-relaxed mb-4">
          In consideration of Your use of the Platform, You agree: 
        </p>
          <ul class="list-disc list-inside">
            <li>(a) that You are of legal age and have the capacity to agree to these Terms and furthermore, if You are a parent / legal guardian of a “minor” then in that event the compliance to the Applicable Law should be adhered to and Company reserves the legal rights to insert necessary protocols / check mechanism to enforce the foregoing including but not limited to the parental / legal guardian’s consent, if required under the Applicable Law and as detailed under the Privacy Policy;</li>
            <li>(b) to provide complete, accurate, current, and required information about You as may be prompted at the time of registration on the Platform ("Personal Data");</li>
            <li>(c) to maintain the security of Your password and identification;</li>
            <li>(d) to maintain and promptly update the Personal Data and any information You provide to Company, to keep it accurate, current and complete for providing the Services.</li>
          </ul>
        
  
        <p class="text-gray-600 leading-relaxed mb-4">
          You are not permitted to use the Platform or submit Content to the Platform if You do not follow these Terms. If You provide any information that is untrue, inaccurate, unauthorized, not current, or incomplete (or becomes untrue, inaccurate, not current, or incomplete), or if the Company has reasonable grounds to suspect that such information is untrue, inaccurate, not current, or incomplete, the Company has the right to refuse any and all the Services.
        </p>
      </section>
      </div>
    </div>
  </div>
</template>

<script setup></script>

<style scoped></style>
